/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db;


import eu.fbk.fm.alignments.index.db.routines.JsonIntext;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>public.json_intext</code>
     */
    public static Object jsonIntext(Configuration configuration, String __1) {
        JsonIntext f = new JsonIntext();
        f.set__1(__1);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>public.json_intext</code> as a field.
     */
    public static Field<Object> jsonIntext(String __1) {
        JsonIntext f = new JsonIntext();
        f.set__1(__1);

        return f.asField();
    }

    /**
     * Get <code>public.json_intext</code> as a field.
     */
    public static Field<Object> jsonIntext(Field<String> __1) {
        JsonIntext f = new JsonIntext();
        f.set__1(__1);

        return f.asField();
    }
}
