/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.udt;


import eu.fbk.fm.alignments.index.db.Public;
import eu.fbk.fm.alignments.index.db.udt.records.TestRecord;

import javax.annotation.Generated;

import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.UDTImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends UDTImpl<TestRecord> {

    private static final long serialVersionUID = 641273527;

    /**
     * The reference instance of <code>public.test</code>
     */
    public static final Test TEST = new Test();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestRecord> getRecordType() {
        return TestRecord.class;
    }

    /**
     * The attribute <code>public.test.k</code>.
     */
    public static final UDTField<TestRecord, Integer> K = createField("k", org.jooq.impl.SQLDataType.INTEGER, TEST, "");

    /**
     * The attribute <code>public.test.v</code>.
     */
    public static final UDTField<TestRecord, String> V = createField("v", org.jooq.impl.SQLDataType.CLOB, TEST, "");

    /**
     * No further instances allowed
     */
    private Test() {
        super("test", null);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }
}
