/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables;


import eu.fbk.fm.alignments.index.db.Keys;
import eu.fbk.fm.alignments.index.db.Public;
import eu.fbk.fm.alignments.index.db.tables.records.UserTextRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserText extends TableImpl<UserTextRecord> {

    private static final long serialVersionUID = 436441581;

    /**
     * The reference instance of <code>public.user_text</code>
     */
    public static final UserText USER_TEXT = new UserText();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserTextRecord> getRecordType() {
        return UserTextRecord.class;
    }

    /**
     * The column <code>public.user_text.uid</code>.
     */
    public final TableField<UserTextRecord, Long> UID = createField("uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_text.text</code>.
     */
    public final TableField<UserTextRecord, String> TEXT = createField("text", org.jooq.impl.SQLDataType.CLOB.nullable(false), this, "");

    /**
     * Create a <code>public.user_text</code> table reference
     */
    public UserText() {
        this("user_text", null);
    }

    /**
     * Create an aliased <code>public.user_text</code> table reference
     */
    public UserText(String alias) {
        this(alias, USER_TEXT);
    }

    private UserText(String alias, Table<UserTextRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserText(String alias, Table<UserTextRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<UserTextRecord> getPrimaryKey() {
        return Keys.USER_TEXT_PKEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<UserTextRecord>> getKeys() {
        return Arrays.<UniqueKey<UserTextRecord>>asList(Keys.USER_TEXT_PKEY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserText as(String alias) {
        return new UserText(alias, this);
    }

    /**
     * Rename this table
     */
    public UserText rename(String name) {
        return new UserText(name, null);
    }
}
