/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.alignments.tables;


import eu.fbk.ict.fm.smt.db.alignments.Keys;
import eu.fbk.ict.fm.smt.db.alignments.tables.records.AlignmentsRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alignments extends TableImpl<AlignmentsRecord> {

    private static final long serialVersionUID = 835566541;

    /**
     * The reference instance of <code>alignments.alignments</code>
     */
    public static final Alignments ALIGNMENTS_ = new Alignments();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AlignmentsRecord> getRecordType() {
        return AlignmentsRecord.class;
    }

    /**
     * The column <code>alignments.alignments.resource_id</code>.
     */
    public final TableField<AlignmentsRecord, String> RESOURCE_ID = createField("resource_id", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>alignments.alignments.twitter_id</code>.
     */
    public final TableField<AlignmentsRecord, Long> TWITTER_ID = createField("twitter_id", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>alignments.alignments.score</code>.
     */
    public final TableField<AlignmentsRecord, String> SCORE = createField("score", org.jooq.impl.SQLDataType.VARCHAR.length(255).nullable(false), this, "");

    /**
     * The column <code>alignments.alignments.is_alignment</code>.
     */
    public final TableField<AlignmentsRecord, Byte> IS_ALIGNMENT = createField("is_alignment", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * Create a <code>alignments.alignments</code> table reference
     */
    public Alignments() {
        this("alignments", null);
    }

    /**
     * Create an aliased <code>alignments.alignments</code> table reference
     */
    public Alignments(String alias) {
        this(alias, ALIGNMENTS_);
    }

    private Alignments(String alias, Table<AlignmentsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Alignments(String alias, Table<AlignmentsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return eu.fbk.ict.fm.smt.db.alignments.Alignments.ALIGNMENTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AlignmentsRecord> getPrimaryKey() {
        return Keys.KEY_ALIGNMENTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AlignmentsRecord>> getKeys() {
        return Arrays.<UniqueKey<AlignmentsRecord>>asList(Keys.KEY_ALIGNMENTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Alignments as(String alias) {
        return new Alignments(alias, this);
    }

    /**
     * Rename this table
     */
    public Alignments rename(String name) {
        return new Alignments(name, null);
    }
}
