/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.old_alignments.tables.records;


import eu.fbk.ict.fm.smt.db.old_alignments.tables.Pages;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PagesRecord extends UpdatableRecordImpl<PagesRecord> implements Record2<String, String> {

    private static final long serialVersionUID = -2038189475;

    /**
     * Setter for <code>twitter_dataset.pages.resource_id</code>.
     */
    public void setResourceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitter_dataset.pages.resource_id</code>.
     */
    public String getResourceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>twitter_dataset.pages.object</code>.
     */
    public void setObject(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitter_dataset.pages.object</code>.
     */
    public String getObject() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<String, String> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Pages.PAGES.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Pages.PAGES.OBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getObject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagesRecord value1(String value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagesRecord value2(String value) {
        setObject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PagesRecord values(String value1, String value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PagesRecord
     */
    public PagesRecord() {
        super(Pages.PAGES);
    }

    /**
     * Create a detached, initialised PagesRecord
     */
    public PagesRecord(String resourceId, String object) {
        super(Pages.PAGES);

        set(0, resourceId);
        set(1, object);
    }
}
