/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.old_alignments.tables.records;


import eu.fbk.ict.fm.smt.db.old_alignments.tables.Tweets;

import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record3;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TweetsRecord extends UpdatableRecordImpl<TweetsRecord> implements Record4<Long, Long, Timestamp, String> {

    private static final long serialVersionUID = -1834137918;

    /**
     * Setter for <code>twitter_dataset.tweets.twitter_id</code>.
     */
    public void setTwitterId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>twitter_dataset.tweets.twitter_id</code>.
     */
    public Long getTwitterId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>twitter_dataset.tweets.tweet_id</code>.
     */
    public void setTweetId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>twitter_dataset.tweets.tweet_id</code>.
     */
    public Long getTweetId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>twitter_dataset.tweets.timestamp</code>.
     */
    public void setTimestamp(Timestamp value) {
        set(2, value);
    }

    /**
     * Getter for <code>twitter_dataset.tweets.timestamp</code>.
     */
    public Timestamp getTimestamp() {
        return (Timestamp) get(2);
    }

    /**
     * Setter for <code>twitter_dataset.tweets.object</code>.
     */
    public void setObject(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>twitter_dataset.tweets.object</code>.
     */
    public String getObject() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record3<Long, Long, Timestamp> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Timestamp, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Long, Long, Timestamp, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return Tweets.TWEETS.TWITTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Tweets.TWEETS.TWEET_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field3() {
        return Tweets.TWEETS.TIMESTAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Tweets.TWEETS.OBJECT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getTwitterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTweetId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value3() {
        return getTimestamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getObject();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TweetsRecord value1(Long value) {
        setTwitterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TweetsRecord value2(Long value) {
        setTweetId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TweetsRecord value3(Timestamp value) {
        setTimestamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TweetsRecord value4(String value) {
        setObject(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public TweetsRecord values(Long value1, Long value2, Timestamp value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TweetsRecord
     */
    public TweetsRecord() {
        super(Tweets.TWEETS);
    }

    /**
     * Create a detached, initialised TweetsRecord
     */
    public TweetsRecord(Long twitterId, Long tweetId, Timestamp timestamp, String object) {
        super(Tweets.TWEETS);

        set(0, twitterId);
        set(1, tweetId);
        set(2, timestamp);
        set(3, object);
    }
}
