/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables.records;


import eu.fbk.fm.alignments.index.db.tables.Alignments;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlignmentsRecord extends UpdatableRecordImpl<AlignmentsRecord> implements Record5<String, Long, Float, Boolean, Short> {

    private static final long serialVersionUID = 2039208839;

    /**
     * Setter for <code>public.alignments.resource_id</code>.
     */
    public void setResourceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.alignments.resource_id</code>.
     */
    public String getResourceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.alignments.uid</code>.
     */
    public void setUid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.alignments.uid</code>.
     */
    public Long getUid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.alignments.score</code>.
     */
    public void setScore(Float value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.alignments.score</code>.
     */
    public Float getScore() {
        return (Float) get(2);
    }

    /**
     * Setter for <code>public.alignments.is_alignment</code>.
     */
    public void setIsAlignment(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.alignments.is_alignment</code>.
     */
    public Boolean getIsAlignment() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>public.alignments.version</code>.
     */
    public void setVersion(Short value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.alignments.version</code>.
     */
    public Short getVersion() {
        return (Short) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Long, Float, Boolean, Short> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, Long, Float, Boolean, Short> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Alignments.ALIGNMENTS.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Alignments.ALIGNMENTS.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Float> field3() {
        return Alignments.ALIGNMENTS.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Alignments.ALIGNMENTS.IS_ALIGNMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Short> field5() {
        return Alignments.ALIGNMENTS.VERSION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Float value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsAlignment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Short value5() {
        return getVersion();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value1(String value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value2(Long value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value3(Float value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value4(Boolean value) {
        setIsAlignment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value5(Short value) {
        setVersion(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord values(String value1, Long value2, Float value3, Boolean value4, Short value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlignmentsRecord
     */
    public AlignmentsRecord() {
        super(Alignments.ALIGNMENTS);
    }

    /**
     * Create a detached, initialised AlignmentsRecord
     */
    public AlignmentsRecord(String resourceId, Long uid, Float score, Boolean isAlignment, Short version) {
        super(Alignments.ALIGNMENTS);

        set(0, resourceId);
        set(1, uid);
        set(2, score);
        set(3, isAlignment);
        set(4, version);
    }
}
