/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables.records;


import eu.fbk.fm.alignments.index.db.tables.UserIndex;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserIndexRecord extends UpdatableRecordImpl<UserIndexRecord> implements Record3<String, Long, Integer> {

    private static final long serialVersionUID = -1612326482;

    /**
     * Setter for <code>public.user_index.fullname</code>.
     */
    public void setFullname(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_index.fullname</code>.
     */
    public String getFullname() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_index.uid</code>.
     */
    public void setUid(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_index.uid</code>.
     */
    public Long getUid() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>public.user_index.freq</code>.
     */
    public void setFreq(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_index.freq</code>.
     */
    public Integer getFreq() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<String, Long, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return UserIndex.USER_INDEX.FULLNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return UserIndex.USER_INDEX.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return UserIndex.USER_INDEX.FREQ;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getFullname();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getFreq();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserIndexRecord value1(String value) {
        setFullname(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserIndexRecord value2(Long value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserIndexRecord value3(Integer value) {
        setFreq(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserIndexRecord values(String value1, Long value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserIndexRecord
     */
    public UserIndexRecord() {
        super(UserIndex.USER_INDEX);
    }

    /**
     * Create a detached, initialised UserIndexRecord
     */
    public UserIndexRecord(String fullname, Long uid, Integer freq) {
        super(UserIndex.USER_INDEX);

        set(0, fullname);
        set(1, uid);
        set(2, freq);
    }
}
