/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db;


import eu.fbk.fm.alignments.index.db.udt.Test;

import javax.annotation.Generated;


/**
 * Convenience access to all UDTs in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UDTs {

    /**
     * The type <code>public.test</code>
     */
    public static Test TEST = eu.fbk.fm.alignments.index.db.udt.Test.TEST;
}
