/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables;


import eu.fbk.fm.alignments.index.db.Public;
import eu.fbk.fm.alignments.index.db.tables.records.UserSgWRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSgW extends TableImpl<UserSgWRecord> {

    private static final long serialVersionUID = 2010115741;

    /**
     * The reference instance of <code>public.user_sg_w</code>
     */
    public static final UserSgW USER_SG_W = new UserSgW();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserSgWRecord> getRecordType() {
        return UserSgWRecord.class;
    }

    /**
     * The column <code>public.user_sg_w.uid</code>.
     */
    public final TableField<UserSgWRecord, Long> UID = createField("uid", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>public.user_sg_w.followees</code>.
     */
    public final TableField<UserSgWRecord, Long[]> FOLLOWEES = createField("followees", org.jooq.impl.SQLDataType.BIGINT.getArrayDataType(), this, "");

    /**
     * Create a <code>public.user_sg_w</code> table reference
     */
    public UserSgW() {
        this("user_sg_w", null);
    }

    /**
     * Create an aliased <code>public.user_sg_w</code> table reference
     */
    public UserSgW(String alias) {
        this(alias, USER_SG_W);
    }

    private UserSgW(String alias, Table<UserSgWRecord> aliased) {
        this(alias, aliased, null);
    }

    private UserSgW(String alias, Table<UserSgWRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Public.PUBLIC;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgW as(String alias) {
        return new UserSgW(alias, this);
    }

    /**
     * Rename this table
     */
    public UserSgW rename(String name) {
        return new UserSgW(name, null);
    }
}
