/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables.records;


import eu.fbk.fm.alignments.index.db.tables.UserSgW;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.TableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSgWRecord extends TableRecordImpl<UserSgWRecord> implements Record2<Long, Long[]> {

    private static final long serialVersionUID = 1933614068;

    /**
     * Setter for <code>public.user_sg_w.uid</code>.
     */
    public void setUid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_sg_w.uid</code>.
     */
    public Long getUid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_sg_w.followees</code>.
     */
    public void setFollowees(Long[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_sg_w.followees</code>.
     */
    public Long[] getFollowees() {
        return (Long[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserSgW.USER_SG_W.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field2() {
        return UserSgW.USER_SG_W.FOLLOWEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value2() {
        return getFollowees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgWRecord value1(Long value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgWRecord value2(Long[] value) {
        setFollowees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgWRecord values(Long value1, Long[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSgWRecord
     */
    public UserSgWRecord() {
        super(UserSgW.USER_SG_W);
    }

    /**
     * Create a detached, initialised UserSgWRecord
     */
    public UserSgWRecord(Long uid, Long[] followees) {
        super(UserSgW.USER_SG_W);

        set(0, uid);
        set(1, followees);
    }
}
