/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.tables.records;


import eu.fbk.fm.alignments.index.db.tables.UserSg;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserSgRecord extends UpdatableRecordImpl<UserSgRecord> implements Record2<Long, Long[]> {

    private static final long serialVersionUID = -1803290885;

    /**
     * Setter for <code>public.user_sg.uid</code>.
     */
    public void setUid(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_sg.uid</code>.
     */
    public Long getUid() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_sg.followees</code>.
     */
    public void setFollowees(Long[] value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_sg.followees</code>.
     */
    public Long[] getFollowees() {
        return (Long[]) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long[]> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<Long, Long[]> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field1() {
        return UserSg.USER_SG.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long[]> field2() {
        return UserSg.USER_SG.FOLLOWEES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long[] value2() {
        return getFollowees();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgRecord value1(Long value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgRecord value2(Long[] value) {
        setFollowees(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UserSgRecord values(Long value1, Long[] value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserSgRecord
     */
    public UserSgRecord() {
        super(UserSg.USER_SG);
    }

    /**
     * Create a detached, initialised UserSgRecord
     */
    public UserSgRecord(Long uid, Long[] followees) {
        super(UserSg.USER_SG);

        set(0, uid);
        set(1, followees);
    }
}
