/**
 * This class is generated by jOOQ
 */
package eu.fbk.fm.alignments.index.db.routines;


import eu.fbk.fm.alignments.index.db.Public;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CubeOut extends AbstractRoutine<Object> {

    private static final long serialVersionUID = -1033578170;

    /**
     * The parameter <code>public.cube_out.RETURN_VALUE</code>.
     */
    public static final Parameter<Object> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.DefaultDataType.getDefaultDataType("cstring"), false, false);

    /**
     * The parameter <code>public.cube_out._1</code>.
     */
    public static final Parameter<Object> _1 = createParameter("_1", org.jooq.impl.DefaultDataType.getDefaultDataType("USER-DEFINED"), false, true);

    /**
     * Create a new routine call instance
     */
    public CubeOut() {
        super("cube_out", Public.PUBLIC, org.jooq.impl.DefaultDataType.getDefaultDataType("cstring"));

        setReturnParameter(RETURN_VALUE);
        addInParameter(_1);
    }

    /**
     * Set the <code>_1</code> parameter IN value to the routine
     */
    public void set__1(Object value) {
        setValue(_1, value);
    }

    /**
     * Set the <code>_1</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void set__1(Field<Object> field) {
        setField(_1, field);
    }
}
