/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.alignments.tables.records;


import eu.fbk.ict.fm.smt.db.alignments.tables.Alignments;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AlignmentsRecord extends UpdatableRecordImpl<AlignmentsRecord> implements Record4<String, Long, String, Byte> {

    private static final long serialVersionUID = -289780243;

    /**
     * Setter for <code>alignments.alignments.resource_id</code>.
     */
    public void setResourceId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>alignments.alignments.resource_id</code>.
     */
    public String getResourceId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>alignments.alignments.twitter_id</code>.
     */
    public void setTwitterId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>alignments.alignments.twitter_id</code>.
     */
    public Long getTwitterId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>alignments.alignments.score</code>.
     */
    public void setScore(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>alignments.alignments.score</code>.
     */
    public String getScore() {
        return (String) get(2);
    }

    /**
     * Setter for <code>alignments.alignments.is_alignment</code>.
     */
    public void setIsAlignment(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>alignments.alignments.is_alignment</code>.
     */
    public Byte getIsAlignment() {
        return (Byte) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, Long> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Long, String, Byte> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<String, Long, String, Byte> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Alignments.ALIGNMENTS_.RESOURCE_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field2() {
        return Alignments.ALIGNMENTS_.TWITTER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Alignments.ALIGNMENTS_.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Alignments.ALIGNMENTS_.IS_ALIGNMENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getResourceId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value2() {
        return getTwitterId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsAlignment();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value1(String value) {
        setResourceId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value2(Long value) {
        setTwitterId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value3(String value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord value4(Byte value) {
        setIsAlignment(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AlignmentsRecord values(String value1, Long value2, String value3, Byte value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AlignmentsRecord
     */
    public AlignmentsRecord() {
        super(Alignments.ALIGNMENTS_);
    }

    /**
     * Create a detached, initialised AlignmentsRecord
     */
    public AlignmentsRecord(String resourceId, Long twitterId, String score, Byte isAlignment) {
        super(Alignments.ALIGNMENTS_);

        set(0, resourceId);
        set(1, twitterId);
        set(2, score);
        set(3, isAlignment);
    }
}
