/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.alignments;


import eu.fbk.ict.fm.smt.db.alignments.tables.Profiles;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Alignments extends SchemaImpl {

    private static final long serialVersionUID = 362063270;

    /**
     * The reference instance of <code>alignments</code>
     */
    public static final Alignments ALIGNMENTS = new Alignments();

    /**
     * The table <code>alignments.alignments</code>.
     */
    public final eu.fbk.ict.fm.smt.db.alignments.tables.Alignments ALIGNMENTS_ = eu.fbk.ict.fm.smt.db.alignments.tables.Alignments.ALIGNMENTS_;

    /**
     * The table <code>alignments.profiles</code>.
     */
    public final Profiles PROFILES = eu.fbk.ict.fm.smt.db.alignments.tables.Profiles.PROFILES;

    /**
     * No further instances allowed
     */
    private Alignments() {
        super("alignments", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            eu.fbk.ict.fm.smt.db.alignments.tables.Alignments.ALIGNMENTS_,
            Profiles.PROFILES);
    }
}
