/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.alignments;


import eu.fbk.ict.fm.smt.db.alignments.tables.Alignments;
import eu.fbk.ict.fm.smt.db.alignments.tables.Profiles;
import eu.fbk.ict.fm.smt.db.alignments.tables.Resources;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in alignments
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>alignments.alignments</code>.
     */
    public static final Alignments ALIGNMENTS_ = eu.fbk.ict.fm.smt.db.alignments.tables.Alignments.ALIGNMENTS_;

    /**
     * The table <code>alignments.profiles</code>.
     */
    public static final Profiles PROFILES = eu.fbk.ict.fm.smt.db.alignments.tables.Profiles.PROFILES;

    /**
     * The table <code>alignments.resources</code>.
     */
    public static final Resources RESOURCES = eu.fbk.ict.fm.smt.db.alignments.tables.Resources.RESOURCES;
}
