/**
 * This class is generated by jOOQ
 */
package eu.fbk.ict.fm.smt.db.old_alignments;


import eu.fbk.ict.fm.smt.db.old_alignments.tables.Alignments;
import eu.fbk.ict.fm.smt.db.old_alignments.tables.Pages;
import eu.fbk.ict.fm.smt.db.old_alignments.tables.Tweets;
import eu.fbk.ict.fm.smt.db.old_alignments.tables.Users;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in twitter_dataset
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.8.4"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>twitter_dataset.alignments</code>.
     */
    public static final Alignments ALIGNMENTS = eu.fbk.ict.fm.smt.db.old_alignments.tables.Alignments.ALIGNMENTS;

    /**
     * The table <code>twitter_dataset.pages</code>.
     */
    public static final Pages PAGES = eu.fbk.ict.fm.smt.db.old_alignments.tables.Pages.PAGES;

    /**
     * The table <code>twitter_dataset.tweets</code>.
     */
    public static final Tweets TWEETS = eu.fbk.ict.fm.smt.db.old_alignments.tables.Tweets.TWEETS;

    /**
     * The table <code>twitter_dataset.users</code>.
     */
    public static final Users USERS = eu.fbk.ict.fm.smt.db.old_alignments.tables.Users.USERS;
}
